project_id = "lcymbetnnuokrijynmjm"

[functions.admin-auth]
verify_jwt = false

[functions.update-booking-status]
verify_jwt = false

[functions.create-payment]
verify_jwt = false

[functions.asaas-webhook]
verify_jwt = false
